"""added vote table

Revision ID: 477b865bfb61
Revises: d121974f6248
Create Date: 2025-05-21 14:47:58.584942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477b865bfb61'
down_revision: Union[str, None] = 'd121974f6248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_owner_id', table_name='posts')
    op.add_column('votes', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'votes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'post_id')
    op.create_index('ix_post_owner_id', 'posts', ['owner_id'], unique=False)
    # ### end Alembic commands ###
